kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kerberos-sidecar-injector
  labels:
    app: kerberos-sidecar-injector
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
