apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kerberos-sidecar-injector
  namespace: das
  labels:
    app: kerberos-sidecar-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kerberos-sidecar-injector
subjects:
- kind: ServiceAccount
  name: kerberos-sidecar-injector
  namespace: das
