apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerberos-sidecar-injector
  # Must be in a ns without istio
  namespace: das
  labels:
    app: kerberos-sidecar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kerberos-sidecar-injector
  template:
    metadata:
      labels:
        app: kerberos-sidecar-injector
    spec:
      serviceAccountName: kerberos-sidecar-injector
      containers:
        - name: kerberos-sidecar-injector
          image: artifactory.cloud.statcan.ca/das-aaw-docker/kerberos-injector:latest
          imagePullPolicy: Always
          args:
          - -service-name=kerberos-sidecar-injector
          - -sidecar-config-file=/etc/webhook/config/sidecarconfig.json
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/prestop.sh"]
          volumeMounts:
          - name: webhook-config
            mountPath: /etc/webhook/config
      volumes:
      - name: webhook-config
        configMap:
          name: kerberos-sidecar-injector-json