apiVersion: v1
kind: Service
metadata:
  name: kerberos-sidecar-injector
  namespace: das
  labels:
    app: kerberos-sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: kerberos-sidecar-injector
